1587036794747	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1587038158800	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1587038158800	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1587038158811	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1587038158814	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1587038161285	Sync.Service	DEBUG	User-Agent: Firefox/75.0 (Linux x86_64) FxSync/1.77.0.20200403170909.desktop
1587038161285	Sync.Service	INFO	Starting sync at 2020-04-16 17:56:01 in browser session r1i1jyc2Bm4Q
1587038161285	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1587038161288	Sync.Status	INFO	Resetting Status.
1587038161288	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1587038161289	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1587038161289	FirefoxAccounts	DEBUG	getOAuthToken enter
1587038161290	FirefoxAccounts	TRACE	getCachedToken returning cached token
1587038161290	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1587038161290	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1587038161305	Sync.Resource	WARN	GET request to https://sync-808-us-west-2.sync.services.mozilla.com/1.5/138338353/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1587038161306	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1587038161307	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1587038161307	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1587038161310	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1587038161313	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
