1586874691699	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1586874790811	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1586874790815	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1586874790830	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1586874790836	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1586874799381	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1586874799382	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1586874799395	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1586874799400	Sync.Service	DEBUG	User-Agent: Firefox/75.0 (Linux x86_64) FxSync/1.77.0.20200403170909.desktop
1586874799400	Sync.Service	INFO	Starting sync at 2020-04-14 20:33:19 in browser session CwGvB8T2YcAs
1586874799401	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1586874799412	Sync.Status	INFO	Resetting Status.
1586874799412	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1586874799414	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1586874800151	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1586874801277	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1586874806279	Sync.Resource	WARN	GET request to https://sync-808-us-west-2.sync.services.mozilla.com/1.5/138338353/info/collections failed: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1586874806280	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1586874806282	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1586874806288	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
